### PR TITLE
Corrected API endpoints

### PR DESCRIPTION
**Pull request by fznsakib**
- Changed API end points as requested

- Can now get nearest trees given a lat, long and radius

- Can now get nearest parks given a lat, long and radius. Parks appear in ascending order of distance. Distance found in metres in 'dist'. Count of unique species (uniqueSpecies) and total trees in park (totalTrees) also provided.

- The API endpoint wiki says `GET /api/v1/parks` should return all parks. Currently I've made it so it only returns all the park codes (IDs) and names, because returning all the data would mean returning the large JSON as it is which would be quite slow. Get the park code you need and use the GET park by code method as required

### CODE REVIEW

**Comment by jalal** [comment]
I like the way McQuistan does it in the tutorial, to have the api files setup as a module. And also to use a config file. Could we do that?
And maybe move the data files out of the way for now, so we would have something like:
```bash
./server|-- app.py
        |-- data/-- *.xml,json
        |-- triffidapi/*.py
```
I think that will give us some flexibility later if we move to a database.

**Comment by jalal** [comment]
Also, I had to add the `requests` module to the virtualenv. I'm not a python person, but can we specify the virtualenv setup somewhere and then just load up from there? Sort of a `package.json`.

**Comment by jalal** [comment]
Also, this does not work:
```
@app.route('/api/v1/parks?lat=<string:lat>&lng=<string:lng>&radius=<string:radius>', methods=['GET'])
```
as it ends up at the route:
```
@app.route('/api/v1/parks', methods=['GET'])
```
I think to work with query strings we need to use the `request` object as per:
http://flask.pocoo.org/docs/1.0/quickstart/#the-request-object

This is better, as it cuts down the number of routing entries that we will have. ie:
```
/parks
/parks/VICTPA
```
and all else is handled with query string arguments.

**Comment by fznsakib** [comment]
Thanks for the pointers, I'll work on it soon

**Comment by jalal** [comment]
I've also taken the liberty of putting up a small test setup, basic at the moment. 3 tests pass, 1 fails.

**Comment by tomwieck** [comment]
> Also, I had to add the `requests` module to the virtualenv. I'm not a python person, but can we specify the virtualenv setup somewhere and then just load up from there? Sort of a `package.json`.

In regards to this we can set up a `requirements.txt` 
Running the `pip freeze` command throws out all the dependencies for the specific virtualenv you're in, so adding the following to that file should just allow us to install using the text file 

```
Click==7.0
Flask==1.0.2
Flask-Cors==3.0.7
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
six==1.12.0
v==4.0.0
Werkzeug==0.14.1
```

Can then use `pip install -r requirements.txt` to install those when setting up the project. 
The above may not be a definitive list, I'm not sure that Jinja2 is required, so might be worth removing it and testing. Let me know if any problems come up!

**Comment by fznsakib** [comment]
Routing issue has been fixed. I found out that for Flask you can't route queried methods differently, so I've kept getAllParks and getNearestParks as different routes. This makes sense to me since getAllParks (only name and code) returns a completely different data structure to getNearestParks (full data on each park), which would mean I would have to do routing to different functions within the route by checking for query parameters.

I will carry on using querying for filtering results, i.e. searching for trees in parks by their Latin code.

I think fetching benches should work now too, since CORS was fixed a while ago

**Comment by jalal** [comment]
If I do:
`pip install -r env/requirements.txt`
then I get the error:
`No matching distribution found for v==4.0.0`
If I comment out line 8 then it's fine.

Apart from that, all good.

**Comment by fznsakib** [comment]
Not sure what package 'v' was. Removed it

**Pull request merged**
