### PR TITLE
Setup basic use of geolocation API.

### PR DESCRIPTION
**Pull request by jalal**
Still needs error handling. Using a vue plugin to wrap the navigator geolocation functions, `vue-browser-geolocation`.

Some cleanup and additions to the Python server API, fixed up the `getNearestParks()` function.

If the device does not have a 'geolocation API', then the Splash screen will display shortly and then we show an alphabetical list of parks.

If there is a 'geolocation API' then we popup a box asking permission to use it. If given, then we find the current device coordinates and then display a list of parks, nearest first. If permission is refused, we display the alphabetical listing.

On selecting a park, we then display the park. We do not center the park on the user unless they click on the Geo centering icon, at which point we then need to `watchPosition()` and handle changes

- [x] Check on first load if we can use the geo API
- [ ] Check if we have high resolution or approximate (WiFi or GPS)
- [x] Find location and load nearest parks
- [ ] If requested, display position in park and track movement.

### CODE REVIEW

**Comment by joshJarr** [comment]
@jalal awesome work!
Annoyingly this is the Exact same task I've been working on, this was in my working list on the project board https://github.com/tomwieck/triffids/issues/33
I know I've been working on this a while, but I've not had allot of free time this last week to put into the project, so I've been chipping away in the evenings. We need to stop working no the same thing, please check the the current task list and ask if there are similar issues, it becomes frustrating and demotivating working on something for so long and realise its duplicated effort.

Would have preferred if you asked my progress and we could have worked on this together.
Silver lining is that we have a similar implementation, so I'll merge our work and push to this branch.

**Comment by jalal** [comment]
@joshJarr Sorry about that. I don't think it's the first time I've trodden on your toes either... in future I'll check what stage you are at with the Project cards. And try and not let feature creep infect what I start off doing.

**Comment by joshJarr** [comment]
@tomwieck @fznsakib @jalal I'd like to get this merged. Just tested across a few devices and it looks good. Can we take a quick gander and get this in?

**Comment by tomwieck** [comment]
This looks good and does work, but I'm worried that once you select it, you are given a list without an option to then view all of the parks. Could we possibly have two lists of parks, or increase the radius big enough so that all parks are still returned?

**Comment by joshJarr** [comment]
Increasing the radius slows down the request massively. Currently the radius increases on scroll (like pagination) to try and fix the slow traffic.
I don't think the radius will go on forever too, I've been finding when testing a max distance of 600 (meters) exists.
We could have two lists, I think that's a nice solution - really think that should be a new task though and not related to this one, maybe it's related to the 'search' task?

- Just trying to reduce the amount of things going on in each PR and minimising scope so we can move faster.

**Comment by joshJarr** [comment]
I've made https://github.com/tomwieck/triffids/issues/63 so will merge this.

**Pull request merged**
